# Generated by Django 4.2 on 2023-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('public', 'PUBLIC')], default='draft', max_length=100),
        ),
    ]
